# Generated by Django 2.2.4 on 2020-07-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lareina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
                ('ubicación', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lascondes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
                ('ubicación', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lobarnechea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
                ('ubicación', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Providencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
                ('ubicación', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vitacura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
                ('ubicación', models.CharField(max_length=100)),
            ],
        ),
    ]
