# Generated by Django 2.2.4 on 2020-07-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0002_sintomas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lareina',
            old_name='ubicación',
            new_name='ubicacion',
        ),
        migrations.RenameField(
            model_name='lascondes',
            old_name='ubicación',
            new_name='ubicacion',
        ),
        migrations.RenameField(
            model_name='lobarnechea',
            old_name='ubicación',
            new_name='ubicacion',
        ),
        migrations.RenameField(
            model_name='providencia',
            old_name='ubicación',
            new_name='ubicacion',
        ),
        migrations.RenameField(
            model_name='vitacura',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
